### ISSUE TITLE
Using port number doesn't work

### ISSUE THREAD

**Issue by neogeno** [hgouveia/node-downloader-helper#1]
If you specify to download from a url with IP:PORT it will crash with  

{ Error: getaddrinfo ENOTFOUND 34.235.190.68:3000 34.235.190.68:3000:3000
   at errnoException (dns.js:53:5)
   at onlookup (dns.js:95:5)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '34.235.190.68:3000',
  host: '34.235.190.68:3000',
  port: '3000' }

**Comment by hgouveia** [comment]
Hello @neogeno I will fix it as soon is possible, if you already have a solution, you are welcome to contribute with a pull request :)

**Comment by hgouveia** [comment]
Hello @neogeno the issue should be fixed now in the 1.0.8 version, please update your package and let me know if worked for you
