### ISSUE TITLE
Add a return on end event for renamed file

### ISSUE THREAD

**Issue by Wetbikeboy2500** [hgouveia/node-downloader-helper#10]
When the override attribute is set to false and a file is downloaded, if there is already a file of that name, it creates a new one with a number attached. This naming convention is handled by the downloader, so there isn't a straightforward way the capture this renamed file or even know the file has been renamed. On the end event, there should be a returned object or value that indicates that the file has been renamed.

**Comment by hgouveia** [comment]
Hello @Wetbikeboy2500 , thanks for you feedback, 

i don't have date estimation to add this functionality but i agree to add those,

for the meantime , what you can do, is use the `fileName` option attribute, this will use the name you provided instead,, so you will need to detect it yourself first, and manage it before create the DownloaderHelper object, and then pass the new name into the options

**Comment by Wetbikeboy2500** [comment]
@hgouveia Thanks, that workaround will be easy. Also, this could be a separate issue but I'll just put it here. The `fileName` rewrites the original file with its extension name. I am currently reading the extension data of the file after downloading to rename it with the correct extension. If 'fileName' only changed the files name and not extension it would be much easier on the process of getting the extension name and renaming which has a higher chances of errors and other bugs.

**Comment by hgouveia** [comment]
Closed, added in version `1.0.11`

**Comment by Chaphasilor** [comment]
> I am currently reading the extension data of the file after downloading to rename it with the correct extension.

Hey @Wetbikeboy2500 would you mind explaining how you do this over in #27? :)
