### ISSUE TITLE
How to continue downloading unfinished files when restarting the program

### ISSUE THREAD

**Issue by ZhangZheng-GIS** [hgouveia/node-downloader-helper#13]
How to continue downloading unfinished files when restarting the program.
Is there a way like fs.appendFile() or fs.createWriteStream(path, { flags: 'a' }) ?

**Comment by hgouveia** [comment]
Hi, @ZhangZheng-GIS 

the package already takes care of this, it actually uses ` fs.createWriteStream(path, { flags: 'a' })`,

but if you restart the program this wont work since it doesnt know anything about the file before, is designed to Resume, when is paused during the download, but this could be improve, to resume if necessary if the file already exists

for the meantime you could do this workaround

```js
const url = 'https://YOUR_URL';
const destFolder  = 'some/path';
const dl = new DownloaderHelper(url, destFolder);

dl.__isResumable =  true; //<--- Workaround

dl
    .on('error' => { dl.resume(); console.log('Download failed, Attempting Retry')´; })
    .on('end', () => console.log('Download Completed'))
    .resume(); // <--- call resume instead of start
```

**Comment by ZhangZheng-GIS** [comment]
> ```js
> dl.__filePath  = 'file/path'; //<--- Workaround
> dl.__isResumable =  true; //<--- Workaround
> ```

It works! Thanks!
But, the progress is not right.
![图片](https://user-images.githubusercontent.com/14178404/60330417-f84dd180-99c4-11e9-8e22-c52b116c2534.png)

**Comment by ZhangZheng-GIS** [comment]
> But, the progress is not right.

It's OK, when I set `dl.__total = total_bytes;`

**Comment by hgouveia** [comment]
> > But, the progress is not right.
> 
> It's fine, when I set `dl.__total = total_bytes;`

great, if you already know the total bytes in advance you can just do that, if not you could request it before 

somehting like

```js
const URL = require('url');
const http = require('http'); // or https

const urlDown = 'http://YOUR_URL';
const destFolder = 'some/path';
const dl = new DownloaderHelper(urlDown, destFolder);

// Get file size
getTotalFileSize(urlDown)
    .then(totalFileSize => {
        dl.__total = totalFileSize; //<--- Workaround
        dl.__filePath = 'file/path'; //<--- Workaround
        dl.__isResumable = true; //<--- Workaround

        dl
            .on('error', (err) => { dl.resume(); console.log('Download failed, Attempting Retry'); })
            .on('end', () => console.log('Download Completed'))
            .resume(); // <--- call resume instead of start
    });

///////----------------------------------
function getTotalFileSize(_url) {
    const urlParse = URL.parse(_url);
    const options = {
        protocol: urlParse.protocol,
        host: urlParse.hostname,
        port: urlParse.port,
        path: urlParse.path,
        method: 'HEAD'
    };

    return new Promise((resolve, reject) => {
        const req = http.request(options, (res) => {
            const { statusCode } = res;

            if (statusCode !== 200) {
                reject(new Error(`Request Failed.Status Code: ${statusCode} `));
            }

            resolve(parseInt(res.headers['content-length']));
        });

        req.end();
    });
}
```

**Comment by IhorVimmi** [comment]
Can anyone help me with this error? I just got code from your example) 

UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, write

`Download failed, Attempting Retry
(node:27868) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, write
(node:27868) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, write
(node:27868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 168)
(node:27868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 168)
Download Completed
`

**Comment by hgouveia** [comment]
@IhorVimmi for what I can see in the logs, it seems you don't have permission over that particularly folder, could you try in another folder?

**Comment by IhorVimmi** [comment]
@hgouveia sorry, i found the solution. i set wrong  dl.__filePath - it should be full with name of file) but i have another question, can i get filename without requests?

**Comment by IhorVimmi** [comment]
@hgouveia thank you man) you save my time) 
But i have another issue
I need to download a few files and display general progress for them. I use a progress event where I calculate total data for files (received and total). 
`.on('progress', (stats) => {
          let total = 0;
          let received = 0;

          for (const item of this.downloadingFilesList[id]) {
            received += stats.downloaded;
            total += stats.total;
          }

          const percent = received / total;
          console.log('per ', total);
        })`

But i got next result

`[1] per  53519535
[1] per  29521491
[1] per  29521491
[1] per  29521491
[1] per  29521491
[1] per  53519535
`
Can u help me with that?

**Comment by IhorVimmi** [comment]
@hgouveia thank you man)

**Comment by hgouveia** [comment]
> @hgouveia thank you man) you save my time)
> But i have another issue
> I need to download a few files and display general progress for them. I use a progress event where I calculate total data for files (received and total).
> `.on('progress', (stats) => {
> let total = 0;
> let received = 0;
> 
> ```
>       for (const item of this.downloadingFilesList[id]) {
>         received += stats.downloaded;
>         total += stats.total;
>       }
> 
>       const percent = received / total;
>       console.log('per ', total);
>     })`
> ```
> 
> But i got next result
> 
> `[1] per 53519535 [1] per 29521491 [1] per 29521491 [1] per 29521491 [1] per 29521491 [1] per 53519535 `
> Can u help me with that?

yeap the thing is that you can't use the same event for all of them you need to create a new DownloadHelper for each one

for example something like this, but all of them will download at the same time,
```
const urlList = ['http://url1', 'http://url1'];
const distFolder = 'some/folder';

const downloadingList = []
let total = 0;
let received = 0;
let startedCount = 0;
let finishedCount = 0;

const started = () => {
    startedCount++;
    if (startedCount === urlList.length) {
        console.log('Started');
    }
};

const finished = () => {
    finished++;
    if (finishedCount === urlList.length) {
        console.log('Started');
    }
};

const progress = (downloaded) => {
    received += downloaded
};

for (const item of urlList) {
    const dl = new DownloadHelper(item, distFolder);
    dl
        .on('download', () => { total += dl.__total; started(); })
        .on('progress', (stats) => progress(stats.downloaded))
        .on('end', () => finished())
        .start();
}
```

you could create a promise queue too, but you will get the totalsize one by one, so in that case is better if check the size for all of them previously , and then call the queue, something like

```
let queue = Promise.resolve();
for (const item of urlList) {
    queue = queue.then(() => new Promise((resolve, reject) => {
        const dl = new DownloadHelper(item, distFolder);
        dl
            .on('progress', (stats) => progress(stats.downloaded))
            .on('end', () => resolve(true))
            .start();
    }));
}
queue.then();
```

**Comment by daniloprates** [comment]
> Hi, @ZhangZheng-GIS
> 
> the package already takes care of this, it actually uses ` fs.createWriteStream(path, { flags: 'a' })`,
> 
> but if you restart the program this wont work since it doesnt know anything about the file before, is designed to Resume, when is paused during the download, but this could be improve, to resume if necessary if the file already exists
> 
> for the meantime you could do this workaround
> 
> ```js
> const url = 'https://YOUR_URL';
> const destFolder  = 'some/path';
> const dl = new DownloaderHelper(url, destFolder);
> 
> dl.__filePath  = 'file/path'; //<--- Workaround
> dl.__isResumable =  true; //<--- Workaround
> 
> dl
>     .on('error' => { dl.resume(); console.log('Download failed, Attempting Retry')´; })
>     .on('end', () => console.log('Download Completed'))
>     .resume(); // <--- call resume instead of start
> ```

I just can't make it work. The resumed download starts to run indefinitely, even after the progress reaches 100%.

**Comment by hgouveia** [comment]
> > Hi, @ZhangZheng-GIS
> > the package already takes care of this, it actually uses ` fs.createWriteStream(path, { flags: 'a' })`,
> > but if you restart the program this wont work since it doesnt know anything about the file before, is designed to Resume, when is paused during the download, but this could be improve, to resume if necessary if the file already exists
> > for the meantime you could do this workaround
> > ```js
> > const url = 'https://YOUR_URL';
> > const destFolder  = 'some/path';
> > const dl = new DownloaderHelper(url, destFolder);
> > 
> > dl.__filePath  = 'file/path'; //<--- Workaround
> > dl.__isResumable =  true; //<--- Workaround
> > 
> > dl
> >     .on('error' => { dl.resume(); console.log('Download failed, Attempting Retry')´; })
> >     .on('end', () => console.log('Download Completed'))
> >     .resume(); // <--- call resume instead of start
> > ```
> 
> I just can't make it work. The resumed download starts to run indefinitely, even after the progress reaches 100%.

Hi @daniloprates could you try using an older version? there were some changes in `1.0.13` so I am wondering if affected this, you could try by install `npm i node-downloader-helper@1.0.12`, if so i would need to take a look, could be a bug

**Comment by daniloprates** [comment]
with `1.0.12` I couldn't make it work at all 😬

**Comment by hgouveia** [comment]
> with `1.0.12` I couldn't make it work at all 😬

this is actually good news, it means I didn't break anything in 1.0.13, so could you paste the code you are using, I assume you want to resume the download using a pre-existing file, correct?

**Comment by daniloprates** [comment]
Great, then :) here's the code: https://github.com/input-output-hk/daedalus/pull/2020/files#diff-48bed83004c5267825882df791304e66R36-R96

**Comment by hgouveia** [comment]
> Great, then :) here's the code: https://github.com/input-output-hk/daedalus/pull/2020/files#diff-48bed83004c5267825882df791304e66R36-R96

Ok! I figure out why it wasn't working, basically, the example you were using is old, and some functionalities ware removed , for example recalculate the downloaded size, this because if you are using pipe for compress the file while downloading, the sizes wont match, so i removed it,

so in a nutshell, you need to recalculate it, here is an example i just did to try this out

```javascript
const path = require('path');
const pkg = require('../package.json');
const { byteHelper } = require('./helpers');
const { DownloaderHelper } = require('../dist');
const url = 'http://www.ovh.net/files/1Gio.dat'; // http://www.ovh.net/files/

const options = {
    headers: {
        'user-agent': pkg.name + '@' + pkg.version
    },
};

const resumeDownload = async () => {
    const dl = new DownloaderHelper(url, __dirname, options);
    const sizeInfo = await dl.getTotalSize(); // get the total size from the server

    dl.__total = sizeInfo.total;
    dl.__filePath = path.join(__dirname, '/' + sizeInfo.name); // path of the existing file
    dl.__downloaded = dl.__getFilesizeInBytes(dl.__filePath);
    dl.__isResumable = true;

    return dl
        .on('error', () => console.log('Download failed'))
        .on('end', () => console.log('Download Completed'))
        .on('progress.throttled', stats => {
            const progress = stats.progress.toFixed(1);
            const speed = byteHelper(stats.speed);
            const downloaded = byteHelper(stats.downloaded);
            const total = byteHelper(stats.total);
            console.log(`${speed}/s - ${progress}% [${downloaded}/${total}]`);
        })
        .resume();
}

resumeDownload();
```

**Comment by daniloprates** [comment]
> Ok! I figure out why it wasn't working, basically, the example you were using is old, and some functionalities ware removed , for example recalculate the downloaded size, this because if you are using pipe for compress the file while downloading, the sizes wont match, so i removed it,

@hgouveia it works 🎉 thanks so much for your support!
