### ISSUE TITLE
Add an event during the downloadRequest phase

### ISSUE THREAD

**Issue by lyswhut** [hgouveia/node-downloader-helper#15]
Hello!
Can you add an event during the `downloadRequest` phase?
When the `downloadRequest` phase request is successful, send an event containing the file information (such as file size) that will be downloaded, so that I can save the file information for recovery download when the event is triggered.

**Comment by hgouveia** [comment]
Hello @lyswhut , there is already an Event when the request succesfully starts, is the **download** event, but not information is sent, i agree that adding this information could be really useful!, i will add it for sure,  btw the Progress Event does has the total file size , so you could listen that one once `dl.once("progress", (stats) => console.log('Filesize;', stats.total));` , and get the filesize or, in the meantime you can try this other workaround 

```js
const url = 'http://YOUR_URL';
const destFolder  = 'some/path';
const dl = new DownloaderHelper(url, destFolder);

dl
    .on('download', => { console.log(`Filename ${dl.__fileName}, Size: ${dl.__total}`); })
    .on('end', () => console.log('Download Completed'))
    .start();
```

**Comment by lyswhut** [comment]
It is recommended that when the request fails, the sent error object is changed to a response object, and then we can decide how to handle the error according to the response.
https://github.com/hgouveia/node-downloader-helper/blob/6f2c5ce87592df405aa1db9fcd0285ded776938f/src/index.js#L168

**Comment by lyswhut** [comment]
Now I have to do this:
```js
onError(err) {
  if (err.message.includes('Response status was')) {
    const code = err.message.replace(/^Response status was (\d+)$/, '$1')
    switch (code) {
      case '401':
      case '403':
      case '410':
        refreshUrl()
        break

      default:
        break
    }
  }
}
```
In some cases, we may also want to get `presonse.body`

**Comment by hgouveia** [comment]
> Now I have to do this:
> 
> ```js
> onError(err) {
>   if (err.message.includes('Response status was')) {
>     const code = err.message.replace(/^Response status was (\d+)$/, '$1')
>     switch (code) {
>       case '401':
>       case '403':
>       case '410':
>         refreshUrl()
>         break
> 
>       default:
>         break
>     }
>   }
> }
> ```
> 
> I didn't find a way to refresh the link, I can only call the internal method now.
> 
> ```js
> dl.url = dl.requestURL = newUrl
> dl.__initProtocol(newUrl)
> dl.resume()
> ```

i willl also add the request error as a second parameter, in onError event,

about the "Refresh URL", is an interesting idea, but not sure if necessary, you could just create a new instance with the new url

**Comment by lyswhut** [comment]
> 
> i willl also add the request error as a second parameter, in onError event,
> 
> about the "Refresh URL", is an interesting idea, but not sure if necessary, you could just create a new instance with the new url

When the URL expires, we need to refresh the URL to resume the download, instead of creating a new instance, what do you think?

**Comment by hgouveia** [comment]
@lyswhut  is an interesting idea, i think is really specific to your case, but doesnt hurt to have this functionality, could you create a separate issue for this?

**Comment by lyswhut** [comment]
I think it should be associated with this problem: https://github.com/hgouveia/node-downloader-helper/issues/13
They all belong to the "Resume Download" feature.
When you resume downloading, you can choose whether to update the URL

**Comment by hgouveia** [comment]
Implemented download info at the 'download' event on v1.0.12
