### ISSUE TITLE
No status change when cut off the network while downloading

### ISSUE THREAD

**Issue by eric8810** [hgouveia/node-downloader-helper#23]
"node-downloader-helper": "^1.0.11"

I try to follow every event, but nothing happen when network cut off and download actrually failed.
![image](https://user-images.githubusercontent.com/756579/75610965-0904a780-5b51-11ea-8838-9c8970245489.png)

Event hang on like pictures above. And nothing happened neither while network back up online.

dl.on('error', err => {
      console.log('download error', err)
    })
    dl.on('stop', err => {
      console.log('download stop', err)
    })
    dl.on('timeout', err => {
      console.log('download timeout', err)
    })
    dl.on('retry', err => {
      console.log('download retry', err)
    })
dl.on('stateChanged', stats => {
      console.log('state changed', stats)
    })

**Comment by hgouveia** [comment]
Hello @eric8810, this seems to be a bug, I will check it and get back to you, thanks!

**Comment by eric8810** [comment]
> Hello @eric8810, this seems to be a bug, I will check it and get back to you,
> 
> do you have any repro steps ?
> 
> thanks!

yes,
1.add listener like I post above
2.start download
3.while downloading, switch off your computer's network(wifi or wired lan)
4.wait and see how events changing.

**Comment by hgouveia** [comment]
Hello @eric8810, I think I might found the issue, I made a fix under dev branch, 

could you validate it is working for you now? you could achieve this installing it in this way `npm i -S  hgouveia/node-downloader-helper#dev`

**Comment by eric8810** [comment]
ok，I will test get you a feedback

**Comment by eric8810** [comment]
sorry to reply late, the commit doesn't seems take effects.
![image](https://user-images.githubusercontent.com/756579/77840135-59097500-71b6-11ea-9d34-8e2a53abaedd.png)


![image](https://user-images.githubusercontent.com/756579/77840140-6a528180-71b6-11ea-9dd6-3dc5ff0a59ef.png)

**Comment by hgouveia** [comment]
@eric8810 strange, for me, is working but I am using Windows, probably is something in OS level, are you using Linux or Mac? 

**_In here I cut out the network and re-enable, so you can see is changed to Failed as it should_**
![electron_ZR4tFi3T3U](https://user-images.githubusercontent.com/668866/77899855-76eddd00-727d-11ea-81ec-5b75ce7376be.png)

**_in here i tried with retry enabled_**
![electron_dpH8PWaxDN](https://user-images.githubusercontent.com/668866/77899777-5756b480-727d-11ea-9ab5-109f259ddb2f.png)


_**Here is the sample code I've used with electron since I believe that's what you are using**_
[downloader.zip](https://github.com/hgouveia/node-downloader-helper/files/4402014/downloader.zip)

**Comment by eric8810** [comment]
![image](https://user-images.githubusercontent.com/756579/78468687-cf751c80-774c-11ea-9d8f-57ca9acf84fe.png)
I'am using your example code, and still the same
platform is macOS catalina 10.15.4

**Comment by hgouveia** [comment]
@eric8810 I've tried my best to try to fix this but I can't found out a solution, it seems is an issue of nodejs on MacOS that I can't fix on my end

but I've found out a workaround,  when you disconnect the network from MacOS , it will emit a timeout , so you could just change the timeout from the options

add this into the downloader options
```
const TIMEOUT = 1000; // in milliseconds
const dl = new DownloaderHelper(url, __dirname, {
    httpRequestOptions: {timeout: TIMEOUT},
    httpsRequestOptions: {timeout: TIMEOUT }
});
dl.on('timeout', () => dl.stop()) 
```

**Comment by eric8810** [comment]
> @eric8810 I've tried my best to try to fix this but I can't found out a solution, it seems is an issue of nodejs on MacOS that I can't fix on my end
> 
> but I've found out a workaround, when you disconnect the network from MacOS , it will emit a timeout , so you could just change the timeout from the options
> 
> add this into the downloader options
> 
> ```
> const TIMEOUT = 1000; // in milliseconds
> const dl = new DownloaderHelper(url, __dirname, {
>     httpRequestOptions: {timeout: TIMEOUT},
>     httpsRequestOptions: {timeout: TIMEOUT }
> });
> dl.on('timeout', () => dl.stop()) 
> ```

Timeout perfectly solve my problem.
Thanks dude. LOL

**Comment by hgouveia** [comment]
> > @eric8810 I've tried my best to try to fix this but I can't found out a solution, it seems is an issue of nodejs on MacOS that I can't fix on my end
> > but I've found out a workaround, when you disconnect the network from MacOS , it will emit a timeout , so you could just change the timeout from the options
> > add this into the downloader options
> > ```
> > const TIMEOUT = 1000; // in milliseconds
> > const dl = new DownloaderHelper(url, __dirname, {
> >     httpRequestOptions: {timeout: TIMEOUT},
> >     httpsRequestOptions: {timeout: TIMEOUT }
> > });
> > dl.on('timeout', () => dl.stop()) 
> > ```
> 
> Timeout perfectly solve my problem.
> Thanks dude. LOL

I am glad you could fix it with this! , closing this, thanks!
