### ISSUE TITLE
Resuming download after restart results in actual file size being incorrect causing corruption

### ISSUE THREAD

**Issue by VTGUS-ZW** [hgouveia/node-downloader-helper#24]
Hello,

I've got some base code setup using what I found in issue [13](https://github.com/hgouveia/node-downloader-helper/issues/13#issue-461898383). However it seems that once the download "resumes" or starts again it doesn't realize the byte size the file already is and just re-downloads the file to the same location/file causing overlap and mismatched byte size. Is the package supposed to detect this once it resumes the download?

```
"DownloadFile": function(url,FullFilePath, FileName) {

    const dl = new DownloaderHelper(url, FullFilePath);

    if (fs.existsSync(FullFilePath + FileName)) {

      functions.getTotalFileSize(url).then(totalFileSize => {

        var stats = fs.statSync(FullFilePath + FileName)

        if (stats["size"] < totalFileSize && stats["size"] != totalFileSize) {

          dl.__total = totalFileSize; //<--- Workaround
          dl.__filePath = FullFilePath + FileName; //<--- Workaround
          dl.__isResumable = true; //<--- Workaround
          // Old Rate: .10MB
          //dl.pipe( new Throttle({ rate: 250000 }) );

          console.log("File found, download not complete, resuming...");
          dl.on('error', (err) => {
            dl.resume(); console.log('Download failed, Attempting Retry');
          }).on('timeout', () => {
            dl.resume(); console.log('Download timed out, Attempting Retry');
          }).on('end', () => {
            console.log('Download Completed');
          }).resume();

        }else{

          console.log("File download is already complete, file is in tact.");

        }

      });

    }else{

      console.log("File not found, starting download...");
      dl.on('error', (err) => {
        dl.resume(); console.log('Download failed, Attempting Retry');
      }).on('timeout', () => {
        dl.resume(); console.log('Download timed out, Attempting Retry');
      }).on('end', () => {
        console.log('Download Completed');
      }).start();

    }

  },

  "getTotalFileSize": function(_url) {
      const urlParse = URLFN.parse(_url);
      const options = {
          protocol: urlParse.protocol,
          host: urlParse.hostname,
          port: urlParse.port,
          path: urlParse.path,
          method: 'HEAD'
      };

      return new Promise((resolve, reject) => {
        const req = http.request(options, (res) => {
            const { statusCode } = res;

            if (statusCode !== 200) {
                reject(new Error(`Request Failed.Status Code: ${statusCode} `));
            }

            console.log(res.headers['content-length']);
            resolve(parseInt(res.headers['content-length']));
        });

        req.end();
    });
  }
```

**Comment by hgouveia** [comment]
Hello @VTGUS-ZW  , yes,  before it calculated the bytes already downloaded automatically, but i removed this since it because if you were using a pipe for example for compress it, the filesize won't match the real downloaded file size, so if you aren't using any pipe, you can add this

```

**Comment by VTGUS-ZW** [comment]
Thank you for your reply, I just added it and it seems that it's throwing an error.. Do you have any suggestions, and or ideas for this error?

```
(node:9996) UnhandledPromiseRejectionWarning: Error: Response status was 416
    at ClientRequest.<anonymous> (D:\@Development\@Node.JS\Agent\node_modules\node-downloader-helper\dist\index.js:1:5974)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at Socket.socketOnData (_http_client.js:452:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
(node:9996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hgouveia** [comment]
> Thank you for your reply, I just added it and it seems that it's throwing an error.. Do you have any suggestions, and or ideas for this error?
> 
> ```
> (node:9996) UnhandledPromiseRejectionWarning: Error: Response status was 416
>     at ClientRequest.<anonymous> (D:\@Development\@Node.JS\Agent\node_modules\node-downloader-helper\dist\index.js:1:5974)
>     at Object.onceWrapper (events.js:288:20)
>     at ClientRequest.emit (events.js:200:13)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
>     at Socket.socketOnData (_http_client.js:452:22)
>     at Socket.emit (events.js:200:13)
>     at addChunk (_stream_readable.js:294:12)
>     at readableAddChunk (_stream_readable.js:275:11)
>     at Socket.Readable.push (_stream_readable.js:210:10)
> (node:9996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:9996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

this is weird, it seems it sent 0 bytes to the resume request, make sure that you put the code i sent you after this

` dl.__filePath = FullFilePath + FileName; //<--- Workaround`

so it will looks like

```
dl.__total = totalFileSize; //<--- Workaround
dl.__filePath = FullFilePath + FileName; //<--- Workaround
dl.__isResumable = true; //<--- Workaround
dl.__downloaded = dl.__getFilesizeInBytes(dl.__filePath);
```

also try to console.log this `dl.__getFilesizeInBytes(dl.__filePath);`  to verify you got the bytes

**Comment by VTGUS-ZW** [comment]
I was able to get it working, thank you! It was an issue with the file that already exists. I just removed that locally and found that it wasn't throwing the error anymore. The file that is local was larger than what it should have been and I believe that was tripping it up.
