### ISSUE TITLE
Response status was 500

### ISSUE THREAD

**Issue by ZhangZheng-GIS** [hgouveia/node-downloader-helper#25]
There are two types of file download links, starting with `http://10.154.3.130/drive/newDownloadFile.do?appFileId=d50996dc730211ea9ac2fa163...` and `http://10.154.3.158:8090becpan5201805111716578384cc46ccf8ae6f43b6a6b5...`.

The former link comes from the server, the latter link downloads the file directly from the Object-based Storage.

The former can be successfully downloaded in the browser, but using `node-downloader-helper` will report an error and return `Response status was 500`.
The latter can be downloaded successfully using `node-downloader-helper`.

Can you help me? Thanks! @hgouveia

**Comment by hgouveia** [comment]
@ZhangZheng-GIS is possible to get the full link of these scenarios? probably just generate 2 public links with any content, for me and then you can remove it

currently, I don't have any Object-based storage to generate such links,

the only issue I see is with this one, `http://10.154.3.158:8090becpan5201805111716578384cc46ccf8ae6f43b6a6b5` , where you might need to separate de port something like `http://10.154.3.158:8090/becpan5201805111716578384cc46ccf8ae6f43b6a6b5` or `http://10.154.3.158:8090?becpan5201805111716578384cc46ccf8ae6f43b6a6b5`

this link should work `http://10.154.3.130/drive/newDownloadFile.do?appFileId=d50996dc730211ea9ac2fa163`...  , do you need to send any header? if so you could specify a custom header in the Downloader options

**Comment by ZhangZheng-GIS** [comment]
`https://pan.cmsoft.com.cn/drive/newDownloadFile.do?appFileId=8a90eb1a748e11eaa0223c78a4d1295a&fileVersion=0&downSource=1&diskType=1&groupId=&comeFrom=10&creatorUsn=3840&isIp=0&corpId=1480&ip=112.25.154.146&userId=zhangzheng_cmss_chinamobile_com&usn=3840&user_Agent=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/80.0.3987.162%20Safari/537.36&isSSL=false&sid=5dad072bc716493aae7402fbb95d60c9&deptId=null&adminType=0`
The above link can be downloaded in chrome, but using `node-downloader-helper` download will be slow and then it will fail.
You can try it, thanks
@hgouveia

**Comment by hgouveia** [comment]
> `https://pan.cmsoft.com.cn/drive/newDownloadFile.do?appFileId=9ad25b4a749811eaa0223c78a4d1295a&fileVersion=0&downSource=1&diskType=1&groupId=&comeFrom=30&creatorUsn=3840&isIp=0&corpId=1480&ip=112.25.154.146&userId=zhangzheng_cmss_chinamobile_com&usn=3840&user_Agent=SKYDWinClient&isSSL=false&sid=08244da052684fafb52942f9f1515057&deptId=null&adminType=0`
> The above link can be downloaded in chrome, but using `node-downloader-helper` download will be slow and then it will fail.
> You can try it, thanks
> @hgouveia

thanks, @ZhangZheng-GIS , I just tried and worked for me, I was able to download it, so it seems at the URL resolution is working, but I would suggest, could you try increasing the timeout? you could do it like this

`const dl = new DownloaderHelper(url, __dirname, { httpsRequestOptions: { timeout: 600000 } })`

the timeout is in milliseconds, if it fails again, please copy the error in here

**Comment by ZhangZheng-GIS** [comment]
`const dl = new DownloaderHelper(url, __dirname, { httpsRequestOptions: { timeout: 600000 } })`
I set it up like this, but after downloading more than ten MB, the ‘end’ event is triggered. Can you download the file completely?
The download speed using a browser is greater than 1MB/s, but using node-downloader-helper is only 40KB/s. Is this the same for you?

**Comment by hgouveia** [comment]
> `const dl = new DownloaderHelper(url, __dirname, { httpsRequestOptions: { timeout: 600000 } })`
> I set it up like this, but after downloading more than ten MB, the ‘end’ event is triggered. Can you download the file completely?
> The download speed using a browser is greater than 1MB/s, but using node-downloader-helper is only 40KB/s. Is this the same for you?

Hello,  yesterday I downloaded around 1gb and the speed was about 1MB/s , but I will try to download the entire thing and let you know my findings

some info on my part:
- I am using Windows 10
- Nodejs 12.6.1 x64

could you verify your node version? are you using Electron?, 
shouldn't be related, but I had some fixes for nonrelated issues, but could you try this version? `npm i -S hgouveia/node-downloader-helper#dev`

I will be today on the chat lobby so we could debug on realtime, https://gitter.im/node-downloader-helper

**Comment by ZhangZheng-GIS** [comment]
Windows 10
nodejs 10.15.0 x64
"electron": "5.0.9"
Used [electron-vue](https://github.com/SimulatedGREG/electron-vue)

Your download speed is normal, it seems to be a problem with my code.
I will try the dev version.
Thx!

**Comment by hgouveia** [comment]
> Windows 10
> nodejs 10.15.0 x64
> "electron": "5.0.9"
> Used [electron-vue](https://github.com/SimulatedGREG/electron-vue)
> 
> Your download speed is normal, it seems to be a problem with my code.
> I will try the dev version.
> Thx!

i suggest you upgrade your electron since you are using a quite old one, the latest electron is using node 12.x

![image](https://user-images.githubusercontent.com/668866/78333936-13202880-758b-11ea-80a8-4e23105daabf.png)

**Comment by hgouveia** [comment]
Closing this issue

we found out that increasing the timeout could help, ex: 
`const dl = new DownloadHelper(url, __dirname, { httpsRequestOptions: { timeout: (1000 * 60 * 60) * 3 } }`

also @ZhangZheng-GIS found out that,  `dl.on('progress', ({ progress, speed, downloaded }) => {...})` could make the download slow, but using a separate function for some reason have better performance, ex:

```
dl.on('progress', printStats(name, startTime));
const printStats = (name, startTime) => {
    return (stats) => {
        const progress = stats.progress.toFixed(1);
        const speed = byteHelper(stats.speed);
        const downloaded = byteHelper(stats.downloaded);
        const total = byteHelper(stats.total);
        // print every one second
        const currentTime = new Date();
        const elaspsedTime = currentTime - startTime;
        if (elaspsedTime > 1000) {
            startTime = currentTime;
            console.log(`[${name}] ${speed}/s - ${progress}% [${downloaded}/${total}]`);
        }
    };
```

I will need to investigate in the future about this progress event, probably a setting to throttle the event that was suggested before by @thelamer

**Comment by ZhangZheng-GIS** [comment]
`error` Event return `Response status was 500` because I did not set `User-Agent ` in the `headers` option.
