### ISSUE TITLE
Is there any options to configure using self-signed certificate?

### ISSUE THREAD

**Issue by agungsijawir** [hgouveia/node-downloader-helper#3]
Hi,

I am using your library and wonder if there is a options to connect to https server using self-signed certificate? thank you!

**Comment by hgouveia** [comment]
Hello @agungsijawir , for now it doesnt support  using self signed, but i will add this option during this week, basically i will allow pass http/https request options, so you can use all options listed on https://nodejs.org/api/https.html#https_https_request_options_callback

using `rejectUnauthorized: false`  or for example

```json
{
 key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
 cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
}
````

i will let you know in this issue ticket, when is done, but for now as workaround you could force nodejs using an Enviroment variable `export NODE_TLS_REJECT_UNAUTHORIZED=0` on unix-like system or `set NODE_TLS_REJECT_UNAUTHORIZED=0`on windows

**Comment by hgouveia** [comment]
Hello @agungsijawir  , i added a fix for this issue,  is now in the **dev**  branch,  please go ahead and download that version as zip file , and just override the folder in yout **node_modules** , 
or using this command 

`npm i -S  git://https://github.com/hgouveia/node-downloader-helper.git#dev`

in other to test, you need to send a option

```javascript
const url = 'https://YOUR_URL';
const destFolder  = 'some/path';
const options = {
  httpsRequestOptions: { rejectUnauthorized : false }
};
const dl = new DownloaderHelper(url, destFolder , options);

dl
    .on('end', () => console.log('Download Completed'))
    .start();
```

if that doesnt work for you, you could specify your selfsigned certificates

```javascript
const options = {
   httpsRequestOptions:  {
            key: fs.readFileSync('keys/key.pem'),
            cert: fs.readFileSync('keys/cert.pem')
   }
}
````
please let me know if that fix the issue for you

**Comment by agungsijawir** [comment]
@hgouveia thank you for your efforts! Will try the these updates!

**Comment by agungsijawir** [comment]
Hi... 

After update to `dev` branch, I got these errors:
```
const { DownloaderHelper } = require('node-downloader-helper');
const dl = new DownloaderHelper('http://ipv4.download.thinkbroadband.com/1GB.zip', __dirname);
 
dl.on('end', () => console.log('Download Completed'))
dl.start();
VM187:1 Uncaught SyntaxError: Identifier 'DownloaderHelper' has already been declared
    at <anonymous>:1:1
```

I am using:
Node Version: 8.9.3
Chrome Version: 61.0.3163.100
Electron Engine Version: 2.0.0

**Comment by agungsijawir** [comment]
Hi @hgouveia ... 

After update to `dev` branch, I got these errors:
```
const { DownloaderHelper } = require('node-downloader-helper');
const dl = new DownloaderHelper('http://ipv4.download.thinkbroadband.com/1GB.zip', __dirname);
 
dl.on('end', () => console.log('Download Completed'))
dl.start();
VM187:1 Uncaught SyntaxError: Identifier 'DownloaderHelper' is not a constructor
    at <anonymous>:1:1
```

I am using:
Node Version: 8.9.3
Chrome Version: 61.0.3163.100
Electron Engine Version: 2.0.0

Any idea ?
