### ISSUE TITLE
Implement Typescript definition

### ISSUE THREAD

**Issue by hgouveia** [hgouveia/node-downloader-helper#30]
Based on the effort already made on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-downloader-helper/index.d.ts

This would need to be placed probably inside `./types/index.d.ts` and defined inside the `package.json` as `"types": "./types/index.d.ts",`

Hello @RemyJeancolas I noticed that you did the definition in DefinitelyTyped, I would like to request if you could consider implementing this inside this repository, so I could to contribute to updating it more frequently

**Comment by geopic** [comment]
Hello, I write type definition files for NPM libraries regularly. Is it ok if I work on this? @RemyJeancolas

**Comment by ls-remy-jeancolas** [comment]
Hi @geopic 👋 

TBH I completely forgot about this, so you are more than welcome to work on it :)

**Comment by hgouveia** [comment]
@geopic you are welcome to contribute! , thanks @ls-remy-jeancolas for you input!

**Comment by geopic** [comment]
Excellent, I'll have it sorted tomorrow :+1:

**Comment by hgouveia** [comment]
Added by @geopic  in PR #38 , thanks!
