### ISSUE TITLE
Ignore invalid https certificates?

### ISSUE THREAD

**Issue by Chaphasilor** [hgouveia/node-downloader-helper#32]
Today I received the following error while trying to download a file:

```node
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
Emitted 'error' event on b instance at:
    at ClientRequest.<anonymous> (C:\Users\Chaphasilor\AppData\Roaming\npm-cache\_npx\37684\node_modules\node-downloader-helper\dist\index.js:1:9035)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

It seems like there's an issue with the ssl certificate, but when I visit the website the browser says the cert is valid.
I also tried downloading the files with `iDownload Manager` from the Microsoft Store, no issues there.

Any ideas on what could cause this and how to work around it? I'd be happy if there was a way to 'ignore' invalid certs (given that HSTS isn't used), but I'm not even sure if this isn't just a strange bug?

**Comment by Chaphasilor** [comment]
To recreate:  

```bash
npx node-downloader-helper . http://megatron.the-breaks.com/movies/%23%23Additions.html
```

**Comment by hgouveia** [comment]
> Today I received the following error while trying to download a file:
> 
> ```js
> events.js:187
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: unable to verify the first certificate
>     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
>     at TLSSocket.emit (events.js:210:5)
>     at TLSSocket._finishInit (_tls_wrap.js:794:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
> Emitted 'error' event on b instance at:
>     at ClientRequest.<anonymous> (C:\Users\Chaphasilor\AppData\Roaming\npm-cache\_npx\37684\node_modules\node-downloader-helper\dist\index.js:1:9035)
>     at ClientRequest.emit (events.js:210:5)
>     at TLSSocket.socketErrorListener (_http_client.js:406:9)
>     at TLSSocket.emit (events.js:210:5)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
> }
> ```
> 
> It seems like there's an issue with the ssl certificate, but when I visit the website the browser says the cert is valid.
> I also tried downloading the files with `iDownload Manager` from the Microsoft Store, no issues there.
> 
> Any ideas on what could cause this and how to work around it? I'd be happy if there was a way to 'ignore' invalid certs (given that HSTS isn't used), but I'm not even sure if this isn't just a strange bug?

I'am no even sure what is causing this, probably node version? probably the website is using some cipher not supported with you current node version 

this library is using raw native http/http request call, and you are able to send options to the request,
so you could use `rejectUnauthorized: false` option in the `httpsRequestOptions`  to see if able to bypass this ex:

```js
const dl = new DownloaderHelper(url,  destFolder, {httpsRequestOptions: {rejectUnauthorized: false} });
```

you can see what `httpsRequestOptions` options you can provide from this url https://nodejs.org/api/https.html#https_https_request_options_callback or https://nodejs.org/api/tls.html#tls_tls_connect_options_callback

in the TLS section, there is also an option to verify yourself the certificates or change the ciphers

**Comment by Chaphasilor** [comment]
Alright, I'll try using a different node version or passing different https options.

I've looked at the node documentation already as explained in the readme, but I find it to be a bit unwieldy most of the time :/ 

I'll let you know how it goes :)

**Comment by Chaphasilor** [comment]
> this library is using raw native http/http request call, and you are able to send options to the request,
> so you could use `rejectUnauthorized: false` option in the `httpsRequestOptions` to see if able to bypass this ex:
> 
> ```js
> const dl = new DownloaderHelper(url,  destFolder, {httpsRequestOptions: {rejectUnauthorized: false} });
> ```

@hgouveia this did the trick! thanks for your help :)
