### ISSUE TITLE
The file cannot use until exit the node process when downloading paused and resume.

### ISSUE THREAD

**Issue by semdy** [hgouveia/node-downloader-helper#44]
env:
  chrome: "87.0.4280.141"
  electron: "11.3.0"
  node: "12.18.3"

The downloaded file is occupied by node or electron when downloading is paused and resume. Accessed when exit electron.

**Comment by semdy** [comment]
The fileStream should be closed when downlading paused.

**Comment by hgouveia** [comment]
Closing, fixed in new version `1.0.18`
https://github.com/hgouveia/node-downloader-helper/releases/tag/v1.0.18
