### ISSUE TITLE
added a background download feature

### ISSUE THREAD

**Issue by nancysavchenkoo** [hgouveia/node-downloader-helper#46]
Can you please add a download feature in the background, so when we switch our browser, the download process will still run on our vps server, it might sound like a cron job.

**Comment by hgouveia** [comment]
hello @nancysavchenkoo this is a functionality is completely possible and not related with the library at all,  you might need to do it in your client, if you are using a framework like angular, vue, react, you could add this logic in a service or store like Vuex/Redux, and it will keep between routes, if you are using electron you can use the ipc message , or if for some reason you have an app where the pages are load from 0 between section you could delegate this to a Shared WebWorker which allows multiple pages from the same domain to share an execution context

if you have further questions, please use the [Discussion ](https://github.com/hgouveia/node-downloader-helper/discussions) section 

i hope this helped
