### ISSUE TITLE
Bandwidth-problem on bigger videos? 

### ISSUE THREAD

**Issue by gklasen** [hgouveia/node-downloader-helper#47]
Hey there, first of all thank for for this nice plugin. I have it installed within an node.js Electron application.

I have the problem, that if i am trying to download bigger videos (like >20 MB maybe?) the plugin starts nicely, but very quickly, performance drops down. I just measured the MB/s for the first 6 seconds:

![image](https://user-images.githubusercontent.com/17546555/113558287-aad1b000-95ff-11eb-80b1-90f274740dfd.png)

Similar behaviour occurs with npm `request` plugin, but works flawlessly as plain browser download. Any chance to solve this by different config etc? 

If not, maybe its solvable via "hack": Funnily If i pause the download every 3 seconds and resume it back, it quickly downloads 7MB-bunches step by step, but unfortunately, output video is malformed afterwards.

**Comment by hgouveia** [comment]
Hello @gklasen , sadly i don´t think this is a issue is related with the library itself and is related with nodejs itself, but i actually use this lib myself in electron and download big files around 6gb be steady speeds

i would suggest to try to use it with plain nodejs without electron and see if you have different results, if so, probably you might need to change electron version or see if there is any solution for this 

i also read that some people where able to get better performance by ussing the  `keepAlive: true` you will need to do thjis in the httpsRequestsOptions, but to be honest i never tried this myself, so let me know if helped, if not helped, sadly i can´t think in any other solution for this situation

```js
const dl = new DownloaderHelper(url, destFolder, {
  httpsRequestOptions: { agent: new https.Agent({keepAlive: true); }
});
```

**Comment by Chaphasilor** [comment]
@gklasen this is a common phenomenon and AFAIK it has to do with the server you're downloading from. Maybe try it with a different download server and see if that helps? :)

**Comment by gklasen** [comment]
Thanks both of you for reply. 

@hgouveia i just tried out the attempt with the "Agent", but did not work out (smaller improvements indeed, but not regarding starting very quickly and then slowing down that much)

I am not trying out with some electron-versions. Can you tell which one you have installed and have no problems with?

@Chaphasilor heard that as well, but still wondering why 1) i am able to download 7 MB within a second, but then slow down so much. I mean, if this is dependant on server alone, wouldnt i have those problems directly from start? And 2) Browser-Download is very quick, from the same server. So i indeed suspect it could be electron somewhere.

**Comment by hgouveia** [comment]
hello @gklasen, for the project i am working on is using Electron 7.3.3

**Comment by gklasen** [comment]
okay, thanks for your support so far.

**Comment by gklasen** [comment]
@hgouveia  Just as last info, was able to resolve and speed it up big time. I switched to "remote.net.request(fileURL)" from Electron. I can imagine this would effect this plugin i a good way to use this as underlying implementation in those cases. If more info is needed, feel free to reach out.
