### ISSUE TITLE
Custom throttle timeout

### ISSUE THREAD

**Issue by SushyDev** [hgouveia/node-downloader-helper#50]
The current throttle time is 1000ms, it would be great if we could configure that to be *ms in the downloader options since 1 second might be long for some usecases

**Comment by hgouveia** [comment]
Hello @SushyDev , you could use the normal `on('progress'` event , this will be triggered as soon it recieved data, and then you can control manually based on your own custom time

but since this have been requested before, i will add an option to change the throttle ms

**Comment by hgouveia** [comment]
Closing, fixed in new version `1.0.18`
https://github.com/hgouveia/node-downloader-helper/releases/tag/v1.0.18
