### ISSUE TITLE
When I download a template project from github, it is not the same as what I expect?

### ISSUE THREAD

**Issue by Inchill** [hgouveia/node-downloader-helper#55]
I used the node-download-helper in my cli to download a vue template project, actually I got a big file, it's not a directory, I am  confused about this issue, can u give me some solutions?

**Comment by hgouveia** [comment]
Hello, @Inchill could you clarify a bit? like how you construct the **DownloadHelper** object? which options? , the **DownloaderHelper** doesn't download folders, just files, so i am a bit confuse

**Comment by Inchill** [comment]
@hgouveia I seem to understand that it doesn't support downloading folders, only individual files, is that right?

**Comment by hgouveia** [comment]
> @hgouveia I seem to understand that it doesn't support downloading folders, only individual files, is that right?

yep you are correct, it only download individual files, if you want to download a entire folder, you will need to get the list of the files from you part and download one by one or if you are the owner of the backend, you can just provided that as a zip files and download the zip file and use the pipe functionality to unzipped them
