### ISSUE TITLE
Error when calling pause or stop method

### ISSUE THREAD

**Issue by Luury** [hgouveia/node-downloader-helper#64]
When I call the `pause()` function using a download object, the following error occurs:

![image](https://user-images.githubusercontent.com/56207672/130898744-95bf5f1c-a592-42c7-8093-cf86dfe77049.png)

what is the correct way to call the function just passing the object?

**Comment by hgouveia** [comment]
@Luury  what i suspect is happening, is that when the download objects are store in vue data, they are treated as browser object, and this library only works in the nodejs context, what i would suggest is just keep the downloader object outside the vue data, and try to map them by id or something that you can call refer to them later

**Comment by Luury** [comment]
@hgouveia,  You're right, that solved the problem.
