### ISSUE TITLE
Node-downloader-helper package is not working in react app

### ISSUE THREAD

**Issue by Vijay-Gurav89** [hgouveia/node-downloader-helper#71]
![20211203_190449](https://user-images.githubusercontent.com/95483631/144611545-f6ba03ba-600f-494c-b80a-9e96ab60c478.jpg)
Getting issue: "TypeError: fs.existsSync is not a function while using this package in react application. Please assist on this issue

**Comment by hgouveia** [comment]
Hello @Vijay-Gurav89  , are you using this into a web page? since `fs.existsSync` is a **nodejs** only function, sadly this library can't be use on browser

**Comment by Vijay-Gurav89** [comment]
Yes I am trying to use this package for web page. So can I use this package in web application?

**Comment by hgouveia** [comment]
> Yes I am trying to use this package for web page. So can I use this package in web application?

Unfortunally is not possible, this is for nodejs base applications only
