### ISSUE TITLE
Workaround for resuming downloads after app restart no longer working with v1.0.19

### ISSUE THREAD

**Issue by AS-Omar** [hgouveia/node-downloader-helper#72]
I was using this workaround you posted for resuming downloads after restarting the Electron app: https://github.com/hgouveia/node-downloader-helper/issues/13#issuecomment-637779060

It was working fine with v1.0.18. However, after upgrading to v1.0.19, this workaround is no longer working and throws an error. Can the workaround be modified so that it works with v1.0.19?

**Comment by Chaphasilor** [comment]
If you could share your code snippet, error message and Node version, I'd take a look at what's going on :)

**Comment by AS-Omar** [comment]
Here's the code snippet (which works with v1.0.18):
```js
downloader = new DownloaderHelper(fileUrl, downloadDirectory, {
  fileName: fileName,
  override: true,
  retry: { maxRetries: 3, delay: 1000 },
  removeOnStop: false,
  removeOnFail: false
})

downloader.__total = fileSize
downloader.__filePath = path.join(downloadDirectory + fileName)
downloader.__downloaded = downloader.__getFilesizeInBytes(downloader.__filePath)
downloader.__isResumable = true

downloader.resume()
```
When I call `downloader.resume()`, I get the this: `TypeError: Cannot read property 'resolve' of null`.

The Node.js version is 14.16.0 (which comes bundled with Electron 13.6.2).

**Comment by Alzar** [comment]
Any fix ever come for this? Running into the same issue with 1.0.19 running Node 16.9.1 (Electron v16.0.7). If I downgrade to v1.0.18 it works without issue

**Comment by Chaphasilor** [comment]
okay so it looks like there's a bit more going on than I initially thought, I'll take a closer look at it over the coming days :)

**Comment by hgouveia** [comment]
@Chaphasilor  is this covered with your PR #76 ?

**Comment by Chaphasilor** [comment]
Nope, didn't get around to this just yet. There was some refactoring and internal method renaming from 1.0.18 to 1.0.19 that seems to be causing this issue...

**Comment by hgouveia** [comment]
@Chaphasilor not a problem, i though was related, i will take a look on my part 👍🏽
