### ISSUE TITLE
url is incomplete

### ISSUE THREAD

**Issue by llh13558455105** [hgouveia/node-downloader-helper#82]
full url：http://xxx.xxx.xx.xx/5865b78a7ecd011273470606ae0f5de4.zip?Expires=1646898756

in  sever-side ：http://xxx.xxx.xx.xx/5865b78a7ecd011273470606ae0f5de4.zip

it lose “Expires=1646898756”！！！

**Comment by hgouveia** [comment]
Implemented on v2.1.0

**Comment by khkassem** [comment]
Hello

It still not working, the same error 400, when I debugged it last time, I have a doubt that the query parameters were not taken, I tested with an url without any query params and it still not working after the update.
I am trying to move to axios, its ok and passing the proxy but i have many 
`Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close in Node Pipeline stream]`

node-downloader-helper was more stable, but this proxy problem is blocking me from using it.

Thank you

**Comment by llh13558455105** [comment]
the same error when i try to resumeFromFile
