### ISSUE TITLE
Silence redirectURL output

### ISSUE THREAD

**Issue by ginsm** [hgouveia/node-downloader-helper#84]
Hey there,

Is there any way to silence the `redirectURL <url> <url>` output? I looked around the README and code but couldn't quite find where it was coming from.

Thanks! :)

**Comment by hgouveia** [comment]
Hello @ginsm , I don't really understand what is the redirectURL output, since it shouldn't output anything, could you send me an example of this?

**Comment by ginsm** [comment]
Hey, thanks for getting back to me. That was my impression while reading the code as well -- I couldn't find anywhere that would cause such an output. Here's an example though:

![image](https://user-images.githubusercontent.com/52685959/158557355-2401654a-2013-4f0b-bbb4-5658e63e3fe9.png)

And here's a gist containing the two files where I'm utilizing `node-downloader-helper` (and my `package.json`):
https://gist.github.com/ginsm/694fc33f8b32e60d79e80357b7ab46f1

I commented out any `console.*` in my program to see if I was accidentally logging something but it still resulted in that strange output. :thinking:

**Comment by hgouveia** [comment]
Hello @ginsm , this is a really weird thing, i am not sure if related with an specific `node.js` version or is there any debug flags, or something related with `*nix` version of node? but i just tried to reproduce it using your code and for me is working fine, 

![image](https://user-images.githubusercontent.com/668866/158573340-267330cd-f48d-4bc0-afc4-885272112266.png)

Could you try to upgrade your `node.js`?, i was using `14.19.0` but you can try any different from your current one, btw there also a new version of the library you might want to upgraded it as well `2.1.0`

**Comment by ginsm** [comment]
I updated `node-downloader-helper` (and `esbuild`) which seems to have resolved the issue (probably should've been one of the first things I did :sweat_smile:). It may have been something to do with `esbuild`? I don't know lol. Either way, it's working as it should now, thank you! :)
