### ISSUE TITLE
downloaded file not completed

### ISSUE THREAD

**Issue by Bluesgavin** [hgouveia/node-downloader-helper#88]
Hi, I downloaded a image using the readme sample. But i got an incomplete image sometime. how can i solve this?

```javascript
const downloader = (url, dir, option) => {
  return new Promise((resolve, reject) => {
    const dl = new DownloaderHelper(url, dir, option);
    dl.on('end', () => {
      resolve(true);
    });
    dl.on('error', (err) => {
      reject(err);
    });
    dl.start().catch((err) => {
      reject(err);
    });
  });
};
dowloader(url,dir,option);
```
![image](https://user-images.githubusercontent.com/41565350/171129978-b999bb02-9d24-47e5-985b-2c7796ce087c.png)

**Comment by Chaphasilor** [comment]
Any errors being logged? Actual URLs would be nice to have for troubleshooting :)

**Comment by Bluesgavin** [comment]
> Any errors being logged? Actual URLs would be nice to have for troubleshooting :)


There's no errors. The end event was normally emitted. 

This is one of the URLs. 
https://dmai-aea.oss-cn-guangzhou.aliyuncs.com/aea/course/c1bdb590-6d26-493e-981c-305f9bf52fb3-.png

**Comment by hgouveia** [comment]
@Bluesgavin unfortunately there is nothing i can't do about this, this seems to be node.js level , is quite common but i just added new behavior that will resume the download if detect is incomplete, please check if solves it for you

**Comment by Bluesgavin** [comment]
> @Bluesgavin unfortunately there is nothing i can't do about this, this seems to be node.js level , is quite common but i just added new behavior in v2.1.2 that will resume the download if detect is incomplete, please check if solves it for you

thank alot for your help 😀
