### ISSUE TITLE
Node.JS versions in CI look stale

### ISSUE THREAD

**Issue by Half-Shot** [hgouveia/node-downloader-helper#90]
A few things popped out at me:

 - Node.JS 15 is out of support
 - Node.JS 18/19 aren't tested (the former being LTS)
 - Publish step currently uses Node 14, which is the [oldest version of Node still supported](https://github.com/hgouveia/node-downloader-helper/blob/master/.github/workflows/npmpublish.yml). It's probably fine for the moment, but should be updated to a newer version soon.

**Comment by hgouveia** [comment]
Upgraded publish actions to node 18 LTS,  v2.1.5
